export function defaultCatch(err: Error): void {
  console.error('caught error', err)
}
